import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/hooks/useAuth";
import localFont from "next/font/local";

// const lufga = localFont({
//   src: [
//     {
//       path: "./../public/fonts/Fontspring-DEMO-lufga-regular.otf", // ✅ option 1 (relative)
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "./../public/fonts/Fontspring-DEMO-lufga-medium.otf",
//       weight: "500",
//       style: "normal",
//     },
//     {
//       path: "./../public/fonts/Fontspring-DEMO-lufga-semibold.otf",
//       weight: "600",
//       style: "normal",
//     },
//   ],
// });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wealth Flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.className} antialiased`}
      >
        <AuthProvider>
        {children}
         </AuthProvider>
      </body>
    </html>
  );
}
